- block:
    - name: install requirements
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
      loop:
        - ca-certificates
        - curl

    - name: install package key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: install docker repo
      ansible.builtin.apt_repository:
        filename: docker.sources
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: install docker
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - docker-compose
  when: ansible_os_family == "Debian"

- block:
    - name: install packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
      loop:
        - docker.io
        - docker-compose
        - docker-buildx
  when: ansible_os_family == "Astra Linux"

- block:
    - name: install repo
      ansible.builtin.yum_repository:
        name: epel
        description: docker repo
        file: external_repos
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  when: ansible_os_family == "RedHat"