- name: create group for docker
  ansible.builtin.group:
    name: docker
    state: present

- name: add ansible user to docker group
  ansible.builtin.user:
    name: 
    groups: docker
    append: true
